### ISSUE TITLE
Images link  in notebook had invalid

### ISSUE THREAD

**Issue by jiangchuan617** [shibing624/nlp-tutorial#2]
<img width="587" alt="image" src="https://github.com/shibing624/nlp-tutorial/assets/31298339/d8cb2de1-607a-4a6a-a58d-c61ad464d14b">
As shown in the picture, many images link had invalid in notebook.
Please fix the link. thank you.

**Comment by shibing624** [comment]
哪个链接的图？

**Comment by jiangchuan617** [comment]
好像是网络问题，挂了梯子又都可以显示了，谢谢哈
